
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      group-id: group_id
    admin:
      properties:
        security.protocol: SSL